In [ ]:
import pandas as pd
import numpy as np
from keras.datasets import mnist

In [ ]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [ ]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(60000, 28, 28)
(10000, 28, 28)
(60000,)
(10000,)


In [ ]:
# Reshaping images from 2D to 1D
X_train = X_train.reshape((X_train.shape[0], -1))
X_test = X_test.reshape((X_test.shape[0], -1))

# Normalize
X_train = X_train / 255.0
X_test = X_test / 255.0

In [ ]:
# One hot encoding
num_classes = len(np.unique(y_train,axis=0))
y_train = np.eye(num_classes)[y_train]
y_test = np.eye(num_classes)[y_test]

In [ ]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(60000, 784)
(10000, 784)
(60000, 10)
(10000, 10)


In [ ]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

In [ ]:
len(X_train[0])

784

In [ ]:
X_train.shape[1]

784

In [ ]:
input_size = X_train.shape[1]
hidden_size = 64
output_size = num_classes

np.random.seed(42)
input_weights = np.random.randn(input_size, hidden_size)
output_weights = np.random.randn(hidden_size, output_size)
bias_input = np.zeros((1, hidden_size))
bias_output = np.zeros((1, output_size))

learning_rate = 0.04
epochs = 20

for epoch in range(epochs):
    for i in range(X_train.shape[0]):
        # Forward pass
        input_data = X_train[i:i+1]
        target = y_train[i:i+1]

        hidden_layer_input = np.dot(input_data, input_weights) + bias_input
        hidden_layer_output = sigmoid(np.dot(input_data, input_weights) + bias_input)

        output_layer_input = np.dot(hidden_layer_output, output_weights) + bias_output
        output_layer_output = sigmoid(output_layer_input)

        # Backpropagation
        output_error = target - output_layer_output
        output_delta = output_error * sigmoid_derivative(output_layer_output)

        hidden_error = output_delta.dot(output_weights.T)
        hidden_delta = hidden_error * sigmoid_derivative(hidden_layer_output)

        # Update weights and biases
        output_weights += hidden_layer_output.T.dot(output_delta) * learning_rate
        bias_output += np.sum(output_delta, axis=0) * learning_rate
        input_weights += input_data.T.dot(hidden_delta) * learning_rate
        bias_input += np.sum(hidden_delta, axis=0) * learning_rate

    # Calculate accuracy
    hidden_layer_input = np.dot(X_test, input_weights) + bias_input
    hidden_layer_output = sigmoid(hidden_layer_input)

    output_layer_input = np.dot(hidden_layer_output, output_weights) + bias_output
    output_layer_output = sigmoid(output_layer_input)

    predictions = np.argmax(output_layer_output, axis=1)
    accuracy = np.mean(predictions == np.argmax(y_test, axis=1))

    print(f'Epoch {epoch+1}/{epochs}, Test Accuracy: {accuracy}')

Epoch 1/20, Test Accuracy: 0.6827
Epoch 2/20, Test Accuracy: 0.7163
Epoch 3/20, Test Accuracy: 0.7288
Epoch 4/20, Test Accuracy: 0.7368
Epoch 5/20, Test Accuracy: 0.8289
Epoch 6/20, Test Accuracy: 0.8359
Epoch 7/20, Test Accuracy: 0.8419
Epoch 8/20, Test Accuracy: 0.8463
Epoch 9/20, Test Accuracy: 0.9022
Epoch 10/20, Test Accuracy: 0.9251
Epoch 11/20, Test Accuracy: 0.9298
Epoch 12/20, Test Accuracy: 0.9322
Epoch 13/20, Test Accuracy: 0.9336
Epoch 14/20, Test Accuracy: 0.936
Epoch 15/20, Test Accuracy: 0.9376
Epoch 16/20, Test Accuracy: 0.9389
Epoch 17/20, Test Accuracy: 0.9407
Epoch 18/20, Test Accuracy: 0.9422
Epoch 19/20, Test Accuracy: 0.9433
Epoch 20/20, Test Accuracy: 0.9445


In [ ]:
from sklearn.metrics import confusion_matrix
conf_matrix = confusion_matrix(np.argmax(output_layer_output, axis=1),  np.argmax(y_test, axis=1))
print("Confusion Matrix:")
print(conf_matrix)

Confusion Matrix:
[[ 963    0   14    4    1    7   14    4   18    9]
 [   0 1113    3    2    1    2    4    6    3    6]
 [   0    5  967   11    2    0    3   18    5    0]
 [   2    1   14  945    0   21    0    8   14    9]
 [   0    1    7    0  935    4    8    2    6   16]
 [   4    3    2   18    1  820   14    2   10    8]
 [   7    4    7    3   11   15  910    1   14    3]
 [   2    1   10   13    4    3    2  963   10    7]
 [   2    7    6    9    6   13    3    6  888   10]
 [   0    0    2    5   21    7    0   18    6  941]]
